name: FlutterCI #CI 名称
on: [push] #触发条件 push 操作！
jobs:
check:
name: Test on ${{ matrix.os }}
# 运行在哪个平台这里是 MacOS 平台
runs - on: macos - latest
steps:
uses: actions/checkout@v1
# 三方 flutter 的 Action，它可以在服务器配置一个 Flutter 环境
uses: subosito/flutter - action@v1
with:
flutter - version: '3.29.0'
channel:'stable'
# 想让我们 CI 做的事情！
run: cd flutteriniosmoudle && flutter build ios - framework --cocoapods --output=../NativePureCocoaPodsDemo/Flutter
run: |
git add.
git commit -m 'update flutter framework'
name: Push changes
uses: ad - m/github - push - action@master
with:
github_token: ${{ secrets.GITHUB_TOKEN }}
